[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :99 -screen 0 1920x1080x24
autostart=true
autorestart=true

[program:celery]
# Added directory parameter so Celery finds your app module
directory=/app
command=bash -c "export DISPLAY=:99 && celery -A tasks worker --loglevel=info --concurrency=1"
autostart=true
autorestart=true


stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0